version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: market_mind
      POSTGRES_USER: market_mind
      POSTGRES_PASSWORD: market_mind
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.24
    environment:
      ALLOW_RESET: "TRUE"
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://market_mind:market_mind@postgres:5432/market_mind
      CHROMA_PERSIST_DIRECTORY: /data/chroma
    depends_on:
      - postgres
      - chroma
    volumes:
      - backend_data:/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:80"

  devcontainer:
    image: python:3.12-bookworm
    volumes:
      - .:/workspaces/market-mind:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: root
    depends_on:
      - postgres
      - chroma

volumes:
  postgres_data:
  chroma_data:
  backend_data:
