replicaCount: 1

image:
  repository: ghcr.io/example/market-mind-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

env:
  VITE_API_URL: "http://market-mind-backend:8000"

ingress:
  enabled: false
  className: ""
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
