replicaCount: 1

image:
  repository: ghcr.io/example/market-mind-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

env:
  VITE_API_URL: "https://market-mind.stackedge.dev/api"

ingress:
  enabled: true
  spec:
    ingressClassName: nginx
  hosts:
    - host: market-mind.stackedge.dev
      paths:
        - path: /portfolio/market-mind/
          pathType: Prefix
  tls:
    - hosts:
        - market-mind.stackedge.dev
      secretName: market-mind-tls

