{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-mind-backend.fullname" . }}-secrets
  labels:
    {{- include "market-mind-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.env.LANGFUSE_PUBLIC_KEY | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.env.LANGFUSE_SECRET_KEY | quote }}
  # DATABASE_URL and CHROMA_URL are intentionally left blank here. When the chart
  # manages Postgres or Chroma, the Deployment will assemble runtime env vars that
  # point to the chart-managed services. To override, set .Values.env.DATABASE_URL
  # and .Values.env.CHROMA_URL in your values.yaml or via --set when installing.
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  CHROMA_URL: {{ .Values.env.CHROMA_URL | quote }}
{{- end }}
