apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-mind-backend.fullname" . }}-secrets
  labels:
    {{- include "market-mind-backend.labels" . | nindent(4) }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.env.LANGFUSE_PUBLIC_KEY | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.env.LANGFUSE_SECRET_KEY | quote }}
