apiVersion: v2
name: market-mind-backend
description: Helm chart for deploying the Market Mind backend service.
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/server.svg

