replicaCount: 1

image:
  repository: gabrielmunumel/market-mind-backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

# Chroma service URL (cluster-internal)
chroma:
  url: http://chroma:8000

env:
  # Sensitive values should not be committed to values.yaml. Leave empty and provide
  # sensitive data via a Kubernetes Secret (recommended) or enable createSecret.
  OPENAI_API_KEY: ""
  OPENAI_MODEL: "gpt-4o"
  DATABASE_URL: ""
  CHROMA_PERSIST_DIRECTORY: /data/chroma
  FRONTEND_ORIGIN: "http://market-mind-frontend"
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
  LANGFUSE_HOST: "https://cloud.langfuse.com"
  HOURLY_REQUEST_LIMIT: "60"
  DAILY_REQUEST_LIMIT: "500"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi

# Postgres (managed by this chart when enabled)
postgres:
  enabled: true
  #useExistingSecret: market-mind-backend-market-mind-backend-postgres
  image:
    repository: postgres
    tag: 15-alpine
  port: 5432
  user: market_mind
  password: market_mind 
  database: market_mind
  persistence:
    enabled: true
    size: 5Gi

# Chroma (managed by this chart when enabled)
chromaService:
  enabled: true
  image:
    repository: ghcr.io/chroma-core/chroma
    tag: 0.4.24
  port: 8000
  allowReset: "TRUE"
  persistence:
    enabled: true
    size: 5Gi

# Secret creation options
createSecret: false
# If you set existingSecretName, the Deployment will reference that Secret for runtime
# env (OPENAI_API_KEY, DATABASE_URL, CHROMA_URL, LANGFUSE_*). Useful when you create
# the secret externally with kubectl or a sealed-secrets controller.
existingSecretName: ""

ingress:
  enabled: true
  spec:
    ingressClassName: nginx
  hosts:
    - host: market-mind.stackedge.dev
      paths:
        - path: /health
          pathType: Prefix
        - path: /api
          pathType: Prefix
        #- path: /api(/|$)(.*)
        #  pathType: Prefix

  tls:
    - hosts:
        - market-mind.stackedge.dev
      secretName: market-mind-tls
