replicaCount: 1

image:
  repository: ghcr.io/example/market-mind-backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

env:
  OPENAI_API_KEY: ""
  OPENAI_MODEL: "gpt-4o"
  DATABASE_URL: "postgresql+psycopg://market_mind:market_mind@postgresql:5432/market_mind"
  CHROMA_PERSIST_DIRECTORY: /data/chroma
  FRONTEND_ORIGIN: "http://market-mind-frontend"
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
  LANGFUSE_HOST: "https://cloud.langfuse.com"
  HOURLY_REQUEST_LIMIT: "60"
  DAILY_REQUEST_LIMIT: "500"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi

ingress:
  enabled: false
  className: ""
  hosts:
    - host: backend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
